# Site settings
title: Home
email: zzh699@gmail.com
description: "This blog is setup for recording knowledges as well as publishing personal affairs."
baseurl: "/myblog"
url: "http://yourdomain.com"
twitter_username: ZhaohengZhang
github_username:  zzh699
highlighter:  pygments

# Build settings
markdown: kramdown
#markdown: redcarpet
#redcarpet:
#	extensions:["tables"]
permalink: pretty
